FROM ubuntu:20.04

WORKDIR /app

ENV DISPLAY :99

RUN apt-get update && \
    apt-get -y install software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get -y install \
    curl \
    # build tools
    build-essential \
    cmake \
    ninja-build \
    pkg-config \
    python3.9 \
    python3.9-dev \
    # required dependencies
    libcurl4-openssl-dev \
    libicu-dev \
    libturbojpeg0-dev \
    libpng-dev \
    libprotobuf-dev \
    libuv1-dev \
    libx11-dev \
    libegl-dev \
    libopengl-dev \
    # runtime dependencies
    xvfb \
    # debugging utilities
    valgrind && \
    # install pip for python3.9
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python3.9 get-pip.py

#  Install python test deps
RUN pip3.9 install pytest pytest-benchmark python-dotenv Pillow numpy pixelmatch requests
