FROM ubuntu:22.04

ARG PYTHON_VERSION="3.12"

WORKDIR /app

ENV DISPLAY :99
ENV LIBGL_ALWAYS_SOFTWARE=1
ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONMALLOC malloc
ENV BUILD_TEMP_DIR /tmp/build
ENV VIRTUAL_ENV /uv/.venv
ENV PATH "/uv/.venv/bin:$PATH"

RUN apt-get update && \
    apt-get -y install \
    curl \
    git \
    # build tools
    build-essential \
    cmake \
    ccache \
    pkg-config \
    # required dependencies
    libcurl4-openssl-dev \
    libicu-dev \
    libjpeg-turbo8-dev \
    libpng-dev \
    libwebp-dev \
    libprotobuf-dev \
    libuv1-dev \
    libx11-dev \
    libegl-dev \
    libopengl-dev \
    libgles2-mesa-dev \
    # runtime dependencies
    xvfb \
    # debugging utilities
    valgrind && \
    /usr/sbin/update-ccache-symlinks

# # Install python and test deps using uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \
    . $HOME/.cargo/env && \
    mkdir /uv && \
    uv python install ${PYTHON_VERSION} && \
    uv venv /uv/.venv

