FROM ubuntu:22.04

WORKDIR /app

ENV DISPLAY :99
ENV DEBIAN_FRONTEND noninteractive
ENV PYTHONMALLOC malloc
ENV BUILD_TEMP_DIR /tmp/build

RUN apt-get update && \
    apt-get -y install software-properties-common && \
    add-apt-repository -y ppa:deadsnakes/ppa && \
    apt-get -y install \
    curl \
    # build tools
    build-essential \
    cmake \
    ccache \
    ninja-build \
    pkg-config \
    # install python 3.10
    python3 \
    python3-dev \
    python3-pip \
    # required dependencies
    libcurl4-openssl-dev \
    libicu-dev \
    libturbojpeg0-dev \
    libpng-dev \
    libprotobuf-dev \
    libuv1-dev \
    libx11-dev \
    libegl-dev \
    libopengl-dev \
    # runtime dependencies
    xvfb \
    # debugging utilities
    valgrind && \
    /usr/sbin/update-ccache-symlinks

#  Install python test deps
RUN python3 -m pip install pytest pytest-benchmark pytest-valgrind python-dotenv Pillow numpy pixelmatch requests

