name: Test on Linux

on: [push, pull_request, workflow_dispatch]

env:
  BUILD_TEMP_DIR: "/build"

jobs:
  test:
    name: Test on ${{ matrix.os }} ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"]
        platform: ["x86_64"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: |
          git submodule update --init
          cd vendor/maplibre-gl-native && \
            git submodule update --init --recursive \
              vendor/earcut.hpp \
              vendor/polylabel \
              vendor/protozero \
              vendor/wagyu \
              vendor/unique_resource \
              vendor/boost \
              vendor/eternal \
              vendor/googletest \
              vendor/mapbox-base

      - name: Install deps
        run: |
          apt-get update
          apt-get -y install software-properties-common
          add-apt-repository -y ppa:deadsnakes/ppa
          apt-get -y install \
            curl \
            build-essential \
            cmake \
            ninja-build \
            pkg-config \
            python3.9 \
            python3.9-dev \
            libcurl4-openssl-dev \
            libicu-dev \
            libturbojpeg0-dev \
            libpng-dev \
            libprotobuf-dev \
            libuv1-dev \
            libx11-dev \
            libegl-dev \
            libopengl-dev \
            xvfb
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3.9 get-pip.py

      - name: Cache build artifacts
        uses: actions/cache@v1
        id: TODO
        with:
          path: /build
          key: ${{ runner.os }}-${{ matrix.platform }}

      - name: Build package
        run: python3.9 setup.py develop

      - name: Run C++ tests
        run: |
          xvfb-run -a --server-args="-screen 0 1024x768x24 -ac +render -noreset" \
            /build/tests/pymgl_test

      - name: Install test deps
        run: pip3.9 install pytest Pillow numpy pixelmatch

      - name: Test package
        run: |
          xvfb-run -a --server-args="-screen 0 1024x768x24 -ac +render -noreset" \
            python3.9 -m pytest pymgl/tests
