name: Test on Linux

on: [push, pull_request, workflow_dispatch]

env:
  BUILD_TEMP_DIR: "/build"

jobs:
  test:
    name: Test on ${{ matrix.os }} ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
        platform: ["x86_64"]
        python-version: ["3.9"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: |
          git submodule update --init
          cd vendor/maplibre-gl-native && \
            git submodule update --init --recursive \
              vendor/earcut.hpp \
              vendor/polylabel \
              vendor/protozero \
              vendor/wagyu \
              vendor/unique_resource \
              vendor/boost \
              vendor/eternal \
              vendor/googletest \
              vendor/mapbox-base \
              vendor/vector-tile

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get -y install software-properties-common
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get -y install \
            curl \
            build-essential \
            cmake \
            ninja-build \
            pkg-config \
            libcurl4-openssl-dev \
            libicu-dev \
            libturbojpeg0-dev \
            libpng-dev \
            libprotobuf-dev \
            libuv1-dev \
            libx11-dev \
            libegl-dev \
            libopengl-dev \
            xvfb

      - name: Cache build artifacts
        uses: actions/cache@v2
        id: pymgl
        with:
          path: ${{ env.BUILD_TEMP_DIR }}
          key: ${{ runner.os }}-${{ matrix.platform }}

      - name: Build package
        run: |
          sudo mkdir -p $BUILD_TEMP_DIR
          sudo chown -R $(id -u):$(id -g) $BUILD_TEMP_DIR
          python setup.py develop

      - name: Run C++ tests
        run: |
          xvfb-run -a --server-args="-screen 0 1024x768x24 -ac +render -noreset" \
            /build/tests/pymgl_test

      - name: Install test deps
        run: python -m pip install pytest Pillow numpy pixelmatch python-dotenv

      - name: Test package
        run: |
          xvfb-run -a --server-args="-screen 0 1024x768x24 -ac +render -noreset" \
            python -m pytest pymgl/tests
